permissions:
  contents: write
name: Build EXE file

on:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Uruchom skrypt konfigurujący środowisko (installResources.ps1)
        shell: pwsh
        run: .\installResources.ps1

      - name: Install Python and PyInstaller
        shell: pwsh
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        shell: pwsh
        run: python -m PyInstaller --onefile main.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-built-exe
          path: dist\project.exe
