permissions:
  contents: write
name: Build EXE file

on:
  schedule:
    # Automatyczne uruchamianie raz w tygodniu, np. w poniedziałek o 2:00 AM UTC 
    - cron: '0 2 * * 1'
  push:
    branches:
      - master
  workflow_dispatch: # ręczne uruchomienie przez użytkownika

jobs:
  build:
    runs-on: windows-latest
    # Domyślny shell to PowerShell, możesz zostawić lub zmienić na bash, np. shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    # 2. Ustawienie Pythona
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Uruchom skrypt konfigurujący środowisko (installResources.ps1)
        shell: pwsh
        run: .\installResources.ps1

      - name: Build executable with PyInstaller
        shell: pwsh
        run: pyinstaller --onefile project.py

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-built-exe
          path: dist\project.exe
