permissions:
  contents: write
name: Build EXE file

on:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Uruchom skrypt konfigurujący środowisko (installResources.ps1)
        shell: pwsh
        run: .\installResources.ps1

      - name: Install Python and PyInstaller
        shell: pwsh
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        shell: pwsh
        run: python -m PyInstaller --onefile --name konwerter-exe main.py

      - name: Commit and push built EXE to main
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/konwerter-exe.exe
          git commit -m "Add/update built konwerter-exe [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-built-exe
          path: dist\konwerter-exe.exe
